quarkus.application.name=rest-locations
quarkus.banner.path=banner.txt

## HTTP configuration
quarkus.http.port=8084
quarkus.http.test-port=0
quarkus.jackson.serialization-inclusion=non-empty
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true

# drop and create the database at startup (use `update` to only update the schema or 'validate' to only validate the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create


## Logging configuration
quarkus.log.category."dev.sbr.location".level=DEBUG
quarkus.log.level=INFO
%dev,test.quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.console.darken=1
%dev,test.quarkus.log.console.level=DEBUG

# OpenTelemetry
quarkus.otel.enabled=false
quarkus.otel.resource.attributes=app=${quarkus.application.name},application=locations-service,system=customers
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.datasource.jdbc.telemetry=true

## CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

# prod configuration
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# OpenAPI
quarkus.smallrye-openapi.info-title=Location API
quarkus.smallrye-openapi.info-description=This API allows CRUD operations on a location
quarkus.smallrye-openapi.info-version=1.0
quarkus.smallrye-openapi.info-contact-name=SBRLLB
quarkus.smallrye-openapi.info-contact-url=https://github.com/sbrllb
quarkus.swagger-ui.always-include=true

