apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-configmap-app-properties
  labels:
    app.kubernetes.io/name: rest-customers
data:
  application.yaml: |
    quarkus:
      datasource.db-kind: oracle
      datasource.reactive.url: vertx-reactive:oracle:thin:@db23cfree-oracle-db23c-free.ora-db.svc.cluster.local:1521/testpdb
      datasource.username: userdev
      datasource.password: mypass
